version: "3"

networks:
  app-network:

services:
  app:
    image: 137021708559.dkr.ecr.us-west-2.amazonaws.com/agent-1:latest
    platform: linux/amd64
    ports:
      - "8511:8501"
    networks:
      - app-network
  
  nginx:
    image: 137021708559.dkr.ecr.us-west-2.amazonaws.com/my-nginx-proxy:latest
    platform: linux/amd64
    ports:
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network
