networks:
  ollama:

services:
  ollama:
    image: ollama/ollama
    networks:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    #network_mode: "host"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - ./data/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    volumes:
      - ./data/pipelines:/app/pipelines
    ports:
      - 9099:9099
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama
    env_file:
      - .env
    restart: always

